version: '2'
services:
  attendance_frontend:
    container_name: attendance_frontend
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certs:/etc/nginx/certs
