"""empty message

Revision ID: 8bde8a6af4b8
Revises: 
Create Date: 2022-12-14 10:32:11.122588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bde8a6af4b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semester'))
    )
    op.create_table('routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('day', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.String(length=100), nullable=False),
    sa.Column('end_time', sa.String(length=100), nullable=False),
    sa.Column('sem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sem_id'], ['semester.id'], name=op.f('fk_routine_sem_id_semester')),
    sa.ForeignKeyConstraint(['sem_id'], ['semester.id'], name=op.f('fk_routine_sem_id_semester'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=2048), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('sem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sem_id'], ['semester.id'], name=op.f('fk_user_sem_id_semester')),
    sa.ForeignKeyConstraint(['sem_id'], ['semester.id'], name=op.f('fk_user_sem_id_semester'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name=op.f('fk_subject_routine_id_routine')),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name=op.f('fk_subject_routine_id_routine'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    op.drop_table('user')
    op.drop_table('routine')
    op.drop_table('semester')
    # ### end Alembic commands ###
