name: Deploy
on: [push, pull_request]
jobs:
  test:
    name: "Backend tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: cd client && npm i && npm run build
      - run: cd server && pip install -r requirements.txt && pytest
  
  deploy:
    name: "Deploy to server"
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps: 
      - run: echo ${{ github.ref }}
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host server 
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Deploy frontend
        run: ssh server 'cd attendance && cd client && git pull origin master && sudo docker-compose up -d --build'
      
      - name: Deploy backend
        run: ssh server 'cd attendance && cd server && git pull origin master && sudo docker-compose up -d --build'